### ISSUE TITLE
How to use and input new data?

### ISSUE THREAD

**Issue by E3V3A** [tipfom/coronaplotter#1]
Please add description on how to use this

**Comment by tipfom** [comment]
I have now added comments and moved the data part up, is this issue resolved or should I take further actions?

**Comment by E3V3A** [comment]
Aha, I see now that you're hard-coded the data into the code. I was hoping to read it from a separate file or or even URL... So never mind. Perhaps a future feature.

**Comment by E3V3A** [comment]
By the way, where did you post those plots. I already forgot how I found this repo... :smile:

**Comment by tipfom** [comment]
Reddit :)

**Comment by tipfom** [comment]
Closed because the data is now gathered automatically
